export interface TarotCard {
  id: number;
  name: string;
  arcana: 'major';
  number: number;
  symbol: string;
  keywords: string[];
  uprightMeaning: string;
  reversedMeaning: string;
  description: string;
  element?: string;
  planet?: string;
  zodiac?: string;
  yesNo: 'yes' | 'no' | 'maybe';
}

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 0,
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    symbol: '0',
    keywords: ['Beginnings', 'Innocence', 'Spontaneity', 'Freedom'],
    uprightMeaning: 'New beginnings, optimism, trust in the universe, innocence, and the courage to leap into the unknown.',
    reversedMeaning: 'Recklessness, naivety, foolishness, risk-taking without forethought.',
    description: 'The Fool stands at the edge of a cliff, ready to step into the unknown. He carries only a small bag, representing unburdened beginnings and pure potential.',
    element: 'Air',
    planet: 'Uranus',
    yesNo: 'yes',
  },
  {
    id: 1,
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    symbol: 'I',
    keywords: ['Manifestation', 'Power', 'Willpower', 'Skill'],
    uprightMeaning: 'Manifestation, resourcefulness, inspired action, and harnessing all available tools to achieve your goals.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents, trickery.',
    description: 'The Magician channels divine power, with one hand pointing to heaven and one to earth. All four suit symbols rest on his table, representing mastery of all elements.',
    element: 'Air',
    planet: 'Mercury',
    yesNo: 'yes',
  },
  {
    id: 2,
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    symbol: 'II',
    keywords: ['Intuition', 'Mystery', 'Wisdom', 'Inner Knowledge'],
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, the subconscious mind, and the mysteries that lie beneath the surface.',
    reversedMeaning: 'Secrets, hidden agendas, ignoring intuition, disconnection from inner voice.',
    description: 'The High Priestess sits between two pillars of the Temple of Solomon, a scroll of spiritual law in her lap, the veil of the subconscious behind her.',
    element: 'Water',
    planet: 'Moon',
    yesNo: 'maybe',
  },
  {
    id: 3,
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    symbol: 'III',
    keywords: ['Fertility', 'Abundance', 'Nature', 'Nurturing'],
    uprightMeaning: 'Femininity, beauty, nature, nurturing, abundance, and the creative force of the universe in full bloom.',
    reversedMeaning: 'Creative block, dependence on others, smothering, lack of growth.',
    description: 'The Empress sits on her throne surrounded by lush nature, embodying the creative and fertile forces of the universe.',
    element: 'Earth',
    planet: 'Venus',
    zodiac: 'Taurus',
    yesNo: 'yes',
  },
  {
    id: 4,
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    symbol: 'IV',
    keywords: ['Authority', 'Structure', 'Control', 'Leadership'],
    uprightMeaning: 'Authority, establishment, structure, a father figure, and the power to manifest desires through focused will.',
    reversedMeaning: 'Tyranny, rigidity, domination, inflexibility, loss of authority.',
    description: 'The Emperor sits on his stone throne, the mountains behind him symbolizing solid foundations and immovable authority.',
    element: 'Fire',
    zodiac: 'Aries',
    yesNo: 'yes',
  },
  {
    id: 5,
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    symbol: 'V',
    keywords: ['Tradition', 'Conformity', 'Morality', 'Spiritual Wisdom'],
    uprightMeaning: 'Spiritual wisdom, religious beliefs, conformity, tradition, and institutions that guide society.',
    reversedMeaning: 'Personal beliefs, freedom, unconventionality, challenging the status quo.',
    description: 'The Hierophant sits between two pillars, raising his right hand in a sacred blessing, bridging heaven and earth.',
    element: 'Earth',
    zodiac: 'Taurus',
    yesNo: 'maybe',
  },
  {
    id: 6,
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    symbol: 'VI',
    keywords: ['Love', 'Harmony', 'Choice', 'Alignment'],
    uprightMeaning: 'Love, harmony, relationships, values alignment, and the deepest choices of the heart.',
    reversedMeaning: 'Self-love deficit, disharmony, imbalance, misalignment of values.',
    description: 'A man and woman stand beneath the angel Raphael, with the Tree of Knowledge behind the woman and the Tree of Life behind the man.',
    element: 'Air',
    zodiac: 'Gemini',
    yesNo: 'yes',
  },
  {
    id: 7,
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    symbol: 'VII',
    keywords: ['Control', 'Willpower', 'Victory', 'Determination'],
    uprightMeaning: 'Control, willpower, success, action, determination, and victory through the mastery of opposing forces.',
    reversedMeaning: 'Lack of control and direction, aggression, obstacles.',
    description: 'The Charioteer drives a chariot pulled by a black and white sphinx, representing the mastery of opposing forces.',
    element: 'Water',
    zodiac: 'Cancer',
    yesNo: 'yes',
  },
  {
    id: 8,
    name: 'Strength',
    arcana: 'major',
    number: 8,
    symbol: 'VIII',
    keywords: ['Courage', 'Inner Strength', 'Patience', 'Compassion'],
    uprightMeaning: 'Courage, inner strength, patience, compassion, and the power of the human spirit over raw nature.',
    reversedMeaning: 'Inner strength doubted, low energy, raw emotion, self-doubt.',
    description: 'A woman gently closes the mouth of a lion, demonstrating that true strength comes from love and compassion, not force.',
    element: 'Fire',
    zodiac: 'Leo',
    yesNo: 'yes',
  },
  {
    id: 9,
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    symbol: 'IX',
    keywords: ['Introspection', 'Solitude', 'Inner Guidance', 'Wisdom'],
    uprightMeaning: 'Soul-searching, introspection, being alone, inner guidance, and the wisdom found in solitude.',
    reversedMeaning: 'Isolation, loneliness, withdrawal, rejection of spiritual guidance.',
    description: 'The Hermit stands atop a mountain holding a lantern, having withdrawn from society to seek inner truth and wisdom.',
    element: 'Earth',
    zodiac: 'Virgo',
    yesNo: 'maybe',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    symbol: 'X',
    keywords: ['Good Luck', 'Karma', 'Life Cycles', 'Destiny'],
    uprightMeaning: 'Good luck, karma, life cycles, destiny, a turning point, and the wheel of fate spinning in your favor.',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles.',
    description: 'The wheel spins with TARO written on it, surrounded by sphinx, serpent, and jackal, representing the cyclic nature of existence.',
    element: 'Fire',
    planet: 'Jupiter',
    yesNo: 'yes',
  },
  {
    id: 11,
    name: 'Justice',
    arcana: 'major',
    number: 11,
    symbol: 'XI',
    keywords: ['Justice', 'Fairness', 'Truth', 'Cause and Effect'],
    uprightMeaning: 'Justice, fairness, truth, cause and effect, and the law of karma ensuring balance is restored.',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty.',
    description: 'Justice sits on her throne, sword in one hand and scales in the other, representing the impartial nature of divine law.',
    element: 'Air',
    zodiac: 'Libra',
    yesNo: 'maybe',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    symbol: 'XII',
    keywords: ['Pause', 'Surrender', 'Letting Go', 'New Perspective'],
    uprightMeaning: 'Pause, surrender, letting go, new perspectives, and the wisdom gained through willing sacrifice.',
    reversedMeaning: 'Delays, resistance, stalling, indecision.',
    description: 'A man hangs upside down from a living tree, his expression serene, suggesting that this voluntary sacrifice leads to enlightenment.',
    element: 'Water',
    planet: 'Neptune',
    yesNo: 'maybe',
  },
  {
    id: 13,
    name: 'Death',
    arcana: 'major',
    number: 13,
    symbol: 'XIII',
    keywords: ['Endings', 'Change', 'Transformation', 'Transition'],
    uprightMeaning: 'Endings, change, transformation, transition, and the inevitable metamorphosis that opens the door to new beginnings.',
    reversedMeaning: 'Resistance to change, stagnation, inability to move on.',
    description: 'Death rides a white horse, symbolizing not physical death but transformation — the ending of one chapter and the beginning of another.',
    element: 'Water',
    zodiac: 'Scorpio',
    yesNo: 'no',
  },
  {
    id: 14,
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    symbol: 'XIV',
    keywords: ['Balance', 'Moderation', 'Patience', 'Purpose'],
    uprightMeaning: 'Balance, moderation, patience, purpose, and the alchemical process of blending opposites into harmony.',
    reversedMeaning: 'Imbalance, excess, self-healing, re-alignment.',
    description: 'An angel pours liquid between two cups, one foot on land and one in water, representing the perfect balance of all elements.',
    element: 'Fire',
    zodiac: 'Sagittarius',
    yesNo: 'yes',
  },
  {
    id: 15,
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    symbol: 'XV',
    keywords: ['Shadow', 'Attachment', 'Materialism', 'Restriction'],
    uprightMeaning: 'Shadow self, attachment, addiction, restriction, and the chains we forge through unconscious patterns.',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment.',
    description: 'Baphomet presides over two chained figures, their chains loose enough to remove — representing self-imposed limitation.',
    element: 'Earth',
    zodiac: 'Capricorn',
    yesNo: 'no',
  },
  {
    id: 16,
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    symbol: 'XVI',
    keywords: ['Sudden Change', 'Upheaval', 'Revelation', 'Chaos'],
    uprightMeaning: 'Sudden change, upheaval, chaos, revelation, and the destruction of false structures to reveal deeper truth.',
    reversedMeaning: 'Personal transformation, fear of change, averting disaster.',
    description: 'Lightning strikes a tower, blowing its crown off and sending figures flying. The tower was built on false foundations and must fall.',
    element: 'Fire',
    planet: 'Mars',
    yesNo: 'no',
  },
  {
    id: 17,
    name: 'The Star',
    arcana: 'major',
    number: 17,
    symbol: 'XVII',
    keywords: ['Hope', 'Faith', 'Renewal', 'Inspiration'],
    uprightMeaning: 'Hope, faith, renewal, inspiration, and the healing power of the cosmic light that guides us home.',
    reversedMeaning: 'Lack of faith, despair, self-trust, disconnection.',
    description: 'A naked woman kneels by water, pouring from two jugs, as stars shine above. She represents pure vulnerability and cosmic connection.',
    element: 'Air',
    zodiac: 'Aquarius',
    yesNo: 'yes',
  },
  {
    id: 18,
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    symbol: 'XVIII',
    keywords: ['Illusion', 'Fear', 'Subconscious', 'Dreams'],
    uprightMeaning: 'Illusion, fear, the subconscious, dreams, and the journey through the darkness to reach the light.',
    reversedMeaning: 'Release of fear, repressed emotion, inner confusion.',
    description: 'The moon illuminates a path between two towers. A wolf and dog howl at the moon while a crayfish emerges from the water below.',
    element: 'Water',
    zodiac: 'Pisces',
    yesNo: 'maybe',
  },
  {
    id: 19,
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    symbol: 'XIX',
    keywords: ['Positivity', 'Fun', 'Warmth', 'Success'],
    uprightMeaning: 'Positivity, fun, warmth, success, vitality, and the pure joy of being alive in the light of your authentic self.',
    reversedMeaning: 'Inner child, feeling down, overly optimistic.',
    description: 'A child rides a horse beneath a radiant sun, sunflowers bloom behind a wall. This is the card of pure joy and enlightenment.',
    element: 'Fire',
    planet: 'Sun',
    yesNo: 'yes',
  },
  {
    id: 20,
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    symbol: 'XX',
    keywords: ['Reflection', 'Reckoning', 'Awakening', 'Absolution'],
    uprightMeaning: 'Reflection, reckoning, awakening, absolution, and the call to rise in response to the universe\'s invitation to transcend.',
    reversedMeaning: 'Self-doubt, inner critic, failure to learn lessons.',
    description: 'The angel Gabriel blows a trumpet, awakening figures rising from their coffins. This is the moment of final reckoning and liberation.',
    element: 'Fire',
    planet: 'Pluto',
    yesNo: 'yes',
  },
  {
    id: 21,
    name: 'The World',
    arcana: 'major',
    number: 21,
    symbol: 'XXI',
    keywords: ['Completion', 'Integration', 'Achievement', 'Wholeness'],
    uprightMeaning: 'Completion, integration, achievement, wholeness, and the triumphant end of a major life cycle.',
    reversedMeaning: 'Seeking personal closure, short-cuts, delays.',
    description: 'A dancing figure wrapped in purple cloth is surrounded by a laurel wreath and four celestial figures, representing the completion of the cosmic journey.',
    element: 'Earth',
    planet: 'Saturn',
    yesNo: 'yes',
  },
];

export function getDailyCard(): TarotCard {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return MAJOR_ARCANA[dayOfYear % MAJOR_ARCANA.length];
}

export function getRandomCard(): TarotCard {
  return MAJOR_ARCANA[Math.floor(Math.random() * MAJOR_ARCANA.length)];
}

// Alias used by app/tarot.tsx
export const getDailyTarotCard = getDailyCard;

export function getCardById(id: number): TarotCard | undefined {
  return MAJOR_ARCANA.find(c => c.id === id);
}
