import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";
import { embeddedOne, type EmbeddedKpi } from "@/lib/supabase/embedded";

export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { orgId, triggeredBy } = await req.json() as { orgId: string; triggeredBy: string };

  const supabase = createServiceClient();

  const [{ data: org }, { data: scores }, { data: items }, { data: chatMsgs }] = await Promise.all([
    supabase.from("organizations").select("name, subscription_tier").eq("id", orgId).single(),
    supabase.from("kpi_scores").select("score, kpi_definitions(name, domain)").eq("org_id", orgId).order("computed_at", { ascending: false }).limit(20),
    supabase.from("action_items").select("title, status").eq("org_id", orgId).order("updated_at", { ascending: false }).limit(10),
    supabase.from("chat_messages").select("content").eq("org_id", orgId).eq("role", "user").order("created_at", { ascending: false }).limit(5),
  ]);

  // Promise.all over heterogeneous query builders erases the row types, so the
  // shapes selected above are restated here.
  const scoreRows = (scores ?? []) as { score: number; kpi_definitions: unknown }[];
  const itemRows = (items ?? []) as { title: string; status: string }[];
  const chatRows = (chatMsgs ?? []) as { content: string }[];

  const scoreLines = scoreRows
    .map((s) => `- ${embeddedOne<EmbeddedKpi>(s.kpi_definitions)?.name ?? "KPI"}: ${s.score.toFixed(1)}/5`)
    .join("\n");

  const topIssues = scoreRows
    .filter((s) => s.score <= 2)
    .slice(0, 3)
    .map((s) => embeddedOne<EmbeddedKpi>(s.kpi_definitions)?.name ?? "Issue")
    .join(", ");

  const openCount = itemRows.filter((i) => i.status === "open").length;
  const doneCount = itemRows.filter((i) => i.status === "complete").length;

  const recentQuestions = chatRows.map((m) => `- ${m.content}`).join("\n");

  const briefing = `# Navigator Briefing — ${org?.name ?? "Unknown Org"}

**Subscription:** ${org?.subscription_tier ?? "unknown"}
**Trigger:** ${triggeredBy}
**Date:** ${new Date().toLocaleDateString()}

## KPI Scores
${scoreLines || "No scores available yet."}

## Top Issues
${topIssues || "None identified"}

## Action Plan Status
- Open items: ${openCount}
- Completed: ${doneCount}

## Recent Questions from User
${recentQuestions || "No chat history."}

---
*Generated by The Navigator · Nomad Consulting*`;

  // Save the handoff event
  await supabase.from("handoff_events").insert({
    org_id: orgId,
    triggered_by: triggeredBy,
    briefing_doc: briefing,
    email_delivered: false,
  });

  // Send email notification (best-effort — log failure but don't block)
  try {
    const nomadEmail = process.env.NOMAD_HANDOFF_EMAIL;
    if (nomadEmail) {
      // In production, replace with your email provider (Resend, SendGrid, etc.)
      // For now we log the briefing; email integration is wired via env var
      console.log(`[HANDOFF] New lead for ${org?.name} → ${nomadEmail}\n${briefing}`);

      await supabase
        .from("handoff_events")
        .update({ email_delivered: true })
        .eq("org_id", orgId)
        .order("submitted_at", { ascending: false })
        .limit(1);
    }
  } catch (err) {
    console.error("[HANDOFF] Email delivery failed:", err);
  }

  return NextResponse.json({ ok: true });
}
